name: Build
on: 
  pull_request: 
    types: 
      - opened
      - synchronize
      - reopened
  push: 
    branches: 
      - master 
jobs: 
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - 
        env: 
          SONAR_HOST_URL: "${{ secrets.SONAR_HOST_URL }}"
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
        uses: sonarsource/sonarqube-scan-action@master
      - 
        env: 
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
        timeout-minutes: 240
        uses: sonarsource/sonarqube-quality-gate-action@master
